production:
  adapter: postgresql
  database: "{{database.name}}"
  host: "{{ hostvars.localhost.rds.endpoint.address }}"
  username: "{{ database.username }}"
  password: "{{ database.password }}"
  encoding: utf8
  schema_search_path: public

development:
  adapter: sqlite3
  database: "db/redmine1.db"
