---
- name: Ensure nginx is at the latest version
  apt: name=nginx state=latest
  become: yes

- name: start nginx
  service:
      name: nginx
      state: started
  become: yes

- name: Uploading redmine config to sites-available
  template:
    src: ./redmine/templates/sites-available
    dest: "/etc/nginx/sites-available/redmine"
    mode: "u=rw,g=r,o=r"
  become: yes

- name: Creating symlink to redmine
  file:
    src: /etc/nginx/sites-available/redmine
    dest: /etc/nginx/sites-enabled/default
    state: link
  become: yes

- name: Restart Nginx
  service:
    name: nginx
    state: restarted
  become: yes
