---
  # - name: Install Ruby Apt Sources
  # apt_repository:
  # repo: ppa:isage-dna/imagick
  # state: present
  # become: yes
- name: Install Ruby Dependancies
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - ruby
    - ruby-bundler
  become: yes
  tags: ruby
