---
- name: Setup RDS Instances required for Redmine
  rds_instance:
    db_name: "{{database.name}}"
    region: us-west-2
    db_instance_class: "db.t2.micro"
    db_instance_identifier: redmine1
    engine: postgres
    storage_type: gp2
    allocated_storage: 20
    publicly_accessible: no
    username: "{{ database.username }}"
    password: "{{ database.password }}"
  register: rds
  tags: rds

- name: "RDS Instances:"
  debug: var=rds
  tags: rds
