---
- name: Checking Redmine.yml thin config exists
  stat:
    path: /etc/thin2.5/redmine.yml
  register: redmine_thin_config_stat_result
  tags: thin

- name: "Ensuring Thin Gems exists"
  gem:
    name: "{{item}}"
    state: present
  with_items: [ "rack" ]
  tags: thin

- name: Ensure Thin is at the latest version
  apt: name=thin state=present
  become: yes
  tags: thin

- name: Removing vendor rubies
  raw: rm -Rf /usr/lib/ruby/vendor_ruby/rack*
  become: yes
  tags: thin

- name: Creating directories for Thin
  file:
    path: "{{item}}"
    state: directory
  become: yes
  with_items: [ "/var/run/redmine", "/var/run/redmine/sockets/", "/var/run/thin/", "/var/log/thin/" ]
  when: redmine_thin_config_stat_result.stat.exists == False
  tags: thin

- name: Ensuring ownership of directories for thin
  raw: "chown www-data:www-data /var/run/redmine/sockets/ /var/run/thin/"
  become: yes
  when: redmine_thin_config_stat_result.stat.exists == False
  tags: thin

- name: Copying LogRotate config for thin
  template:
    src: ./thin/templates/logrotate.thin
    dest: "/etc/logrotate.d/thin"
    mode: "u=rw,g=r,o=r"
  become: yes
  when: redmine_thin_config_stat_result.stat.exists == False
  tags: thin

- name: Setup init.d for Thin
  blockinfile:
      path: "/etc/init.d/thin"
      block: |
        pre-start script
            mkdir -p -m0755 /var/run/redmine
            mkdir -p -m0755 /var/run/redmine/sockets
            mkdir -p -m0755 /var/run/thin
            chown www-data:www-data /var/run/redmine/sockets
            chown www-data:www-data /var/run/thin
        end script
      insertbefore: "DAEMON=/usr/bin/thin"
      state: present
      create: yes
  become: yes
  when: redmine_thin_config_stat_result.stat.exists == False
  tags: thin

- name: Start Thin Config
  raw: "thin config --chdir /usr/share/redmine --config /etc/thin2.5/redmine.yml --environment production --socket /var/run/redmine/sockets/thin.sock --daemonize --log /var/log/thin/redmine.log --pid /var/run/thin/redmine.pid --user www-data --group www-data --servers 1 --prefix /redmine"
  become: yes
  when: redmine_thin_config_stat_result.stat.exists == False
  tags: thin

- name: Restart Thin
  service:
    name: thin
    state: restarted
  become: yes
  tags: thin
