---
- name: "Checking redmine-4.0.0 tarball exists"
  stat:
    path: "/home/{{webservers.ssh_user}}/redmine-4.0.0.tar.gz"
  register: redmine_tarball_stat_result

- name: Checking redmine-4.0.0 folder exists
  stat:
    path: "/home/{{webservers.ssh_user}}/redmine-4.0.0"
  register: redmine_src_folder_stat_result

- name: Create the file, if it doesnt exist already
  get_url:
    url: "http://www.redmine.org/releases/redmine-4.0.0.tar.gz"
    dest: "/home/{{webservers.ssh_user}}/redmine-4.0.0.tar.gz"
  when: redmine_src_folder_stat_result.stat.exists == False and redmine_tarball_stat_result.stat.exists == False 

- name: Unarchiving redmine tarball
  unarchive:
    src: "/home/{{webservers.ssh_user}}/redmine-4.0.0.tar.gz"
    dest: "/home/{{webservers.ssh_user}}"
    remote_src: yes
  when: redmine_src_folder_stat_result.stat.exists == False

- name: "RDS Vars: "
  debug: var=hostvars.localhost.rds

- name: "WebServer Vars: "
  debug: var=webservers

- name: Uploading database.yml
  template:
    src: ./redmine/templates/database.yml
    dest: "/home/{{webservers.ssh_user}}/redmine-4.0.0.tar.gz"
    owner: "{{webservers.ssh_user}}"
    mode: "u=rw,g=r,o=r"

- name: Setup gems for Redmine
  bundler:
    state: present
    gemfile: "/home/{{webservers.ssh_user}}/redmine-4.0.0/Gemfile"
