---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    product: redmine
    product_version: "4.0"
    region: us-west-2
    keypair: redmine-ec2-keypair
    ami_image_id: "ami-0bbe6b35405ecebdb"  # Ubuntu 18.04 LTS
  tasks:
    - name: Setup EC2 Instances required for Redmine
      ec2:
        keypair: "{{ keypair }}"
        image: "{{ ami_image_id }}"
        region: "{{ region }}"
        instance_type: t1.micro
        exact_count: 1
        group: webserver_group
        wait: true
        count_tag: 
            Product: "{{ product }}"
            Version: "{{ product_version }}"
        instance_tags: 
            Product: "{{ product }}"
            Version: "{{ product_version }}"
      register: ec2
      delegate_to: localhost

    - name: "EC2 Instances:"
      debug: var=ec2

    - name: "RDS Instances:"
      debug: var=rds

    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      lineinfile:
          dest: "./hosts" 
          regexp: "{{ item.public_ip }}"
          insertafter: "[webservers]"
          line: "{{ item.public_ip }}"
          state: present
          create: yes
      with_items: "{{ ec2.tagged_instances }}"
      delegate_to: localhost

    - name: Wait for SSH to come up
      wait_for:
        host: "{{ item.public_ip }}"
        port: 22 
        state: started
      with_items: "{{ ec2.tagged_instances }}"
      delegate_to: localhost

    - name: Add tag to Instance(s)
      ec2_tag:
          resource: "{{ item.id }}"
          region: "{{ region }}"
          state: present
      with_items: "{{ ec2.tagged_instances }}"
      args:
        tags:
          Name: webserver
      delegate_to: localhost
