---
- hosts: webservers
  gather_facts: False
  vars_files:
    - vars.yml
  tasks:
    - name: Ensure python exists
      raw: test -e /usr/bin/python || (apt-get -y update && apt-get --yes install software-properties-common && apt-get install -y python2.7 python-pip)
      become: yes
