---
- hosts: webservers
  gather_facts: False
  vars_files:
    - vars.yml
  tasks:
    - name: Install Ruby Dependancies
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
        - ruby
        - ruby-bundler
      become: yes
      tags: python
