webservers:
    keypair: redmine-ec2-keypair
    private_keyfile: "~/.liftoff/keyfiles/redmine/redmine-ec2-keypair.pem"
    ssh_user: ubuntu

ansible_ssh_private_key_file: "{{ webservers.private_keyfile }}"
ansible_user: "{{ webservers.ssh_user }}"
