webservers:
    keypair: redmine-ec2-keypair
    private_keyfile: "~/.liftoff/keyfiles/redmine/redmine-ec2-keypair.pem"
    ssh_user: ubuntu

database:
    name: redmine1
    username: redmine
    password: redminepassword

ruby_install_version: 0.7.0
ansible_ssh_private_key_file: "{{ webservers.private_keyfile }}"
ansible_user: "{{ webservers.ssh_user }}"
